apiVersion: v1
kind: Service
metadata:
  name: devraq-oras-skopeo-api-svc
  namespace: thinkcloud
  labels:
    app: devraq-oras-skopeo-api
spec:
  type: ClusterIP
  selector:
    app: devraq-oras-skopeo-api
  ports:
    - port: 8009
      targetPort: 8009
      protocol: TCP
