apiVersion: v1
kind: Service
metadata:
  name: devraq-oras-skopeo-api
  namespace: default
  labels:
    app: devraq-oras-skopeo-api
spec:
  type: ClusterIP
  selector:
    app: devraq-oras-skopeo-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
